### ISSUE TITLE
Boleto Santander

### ISSUE THREAD

**Issue by guilhermearajorocha** [Romulosanttos/gerar-boletos#1]
Boa tarde, está gerando o erro:
(node:13120) UnhandledPromiseRejectionWarning: Error: Erro na geração do código de barras. Número de dígitos diferente de 44. Verifique se todos os dados foram preenchidos corretamente. Tamanho encontrado: 46

Isso é ao gerar o boleto Santander.

**Comment by Romulosanttos** [comment]
boa noite, desculpa a demora para responder.
mas conseguiu encontrar uma solução ?

normalmente esse erro acontece, quando algum dado esta sendo passado mal formatado.
suposição: você tem do banco o nosso número 0001, porém ele precisa que 00000001.
sendo assim ele necessita de 8 dígitos no campo informado.

**Comment by Romulosanttos** [comment]
boa noite, estou fechando a tarefa. é logo mais colocarei mais exemplos
