### ISSUE TITLE
Teste boleto Sicoob

### ISSUE THREAD

**Issue by christianjorge12** [Romulosanttos/gerar-boletos#14]
Estou tentando testar a geração de boletos pelo Sicoob porém está acontecendo um problema com as datas. Ao rodar o `npm run test` com a package.json configurada para pegar o script do sicoob-test.js é dado o seguinte erro: 

TypeError: data.getFullYear is not a function
    at validarData (gerar-boletos-master/lib/utils/functions/boletoUtils.js:361:18)
    at Datas.comDocumento (gerar-boletos-master/lib/utils/functions/boletoUtils.js:377:8)
    at Object.setUp (gerar-boletos-master/tests/boleto/bancos/sicoob-test.js:21:9) [ etc...]

Sabe por que?

**Comment by Romulosanttos** [comment]
Boa noite, ficou pendente de ajusta os caminhos no testes. pois reformulei algumas coisas recentes.

recomento usar da uma olhada no arquivo examples/gerar-boleto-cecred.js. lá tem um exemplo funcional

**Comment by Romulosanttos** [comment]
@christianjorge12  criei uma nova tarefa #15 para fazer as correções no testes do código legado

**Comment by christianjorge12** [comment]
Irei fazer o teste e qualquer ponderação relato aqui. Obrigado!
