### ISSUE TITLE
Exemplo Caixa

### ISSUE THREAD

**Issue by Davidiasdesousa** [Romulosanttos/gerar-boletos#2]
Por gentileza, poderia criar um exemplo pro banco Caixa? 
Estou tentando gerar, porém não estou conseguindo e quando consigo, não dá pra pagar...
Agradeço a atenção...

**Comment by Romulosanttos** [comment]
Boa noite, você fez a integração com a caixa para registrar o boleto ? pois só vai ser possivel fazer o pagamento do boleto uma vez que ele estiver registrado. Se puder explicar melhor agradeço.

Desculpe a demora para responder

**Comment by teomarcus** [comment]
De qualquer maneira, acredito que a geração de boletos para a Caixa não está implementada corretamente. Tenho um sistema legado que gera boletos para a Caixa e estou tentando usar os mesmos valores nos testes mas, este módulo está gerando um código de 45 dígitos, retornando um erro em valida-codigo-barras.js.
