### ISSUE TITLE
Atualizar versao no npm

### ISSUE THREAD

**Issue by IgorDePaula** [Romulosanttos/gerar-boletos#20]
Bom dia, eu fui testar sua lib mas acabei nao conseguindo, pois os exemplos estao pra versao 1.4.4, mas no npm so consigo baixar a versao 1.3.3.

**Comment by Romulosanttos** [comment]
Boa noite, acabei esquecendo de atualizar lá. estarei fazendo hoje.

**Comment by Romulosanttos** [comment]
@IgorDePaula https://www.npmjs.com/package/gerar-boletos atualizado para versão 1.4.5

**Comment by IgorDePaula** [comment]
@Romulosanttos Show de bola, vou testar e te trago feedback.

**Comment by IgorDePaula** [comment]
Achei uma melhoria e vou fazer um PR.
