### ISSUE TITLE
Remessa e retorno

### ISSUE THREAD

**Issue by SuportecTL** [Romulosanttos/gerar-boletos#21]
Boa tarde, gostaria de saber se a lib gera remessa e processa retorno dos bancos que já estão implementados.

**Comment by IgorMoraes15** [comment]
Boa tarde... Também tenho a mesma dúvida! Valeu

**Comment by Romulosanttos** [comment]
boa noite @SuportecTL  @IgorMoraes15 . 

No momento, Não. mas está no planejamento. Acredito que seria um novo projeto que esse teria dependência do mesmo.
