### ISSUE TITLE
Caractere inválido

### ISSUE THREAD

**Issue by ezequielvictor** [Romulosanttos/gerar-boletos#6]
Olá, emiti um boleto e fui validar no sistema do banco do Itaú, como teste para validação.
O sistema retornou: `Caractere inválido 162 código 1`
Pelo que vi na documentação na página 22 o erro se refere a isto:
(F) Informar o valor por dia de atraso nas posições 161 a 173 e a data nas posições 386 a 391. 

Porém nao achei onde coloco este valor, nao sei se realmente é isso também, poderia me ajudar/informar?

**Comment by Romulosanttos** [comment]
boa noite, @ezequielvictor conseguiu solucionar ? 

caso positivo, se puder deixar como foi solucionado, pode ser interessante para pessoas que tiverem error parecido 

:)
